blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('search/', views.blog, name='search'),
    path('', views.blog, name='blog'),
    path('blog_details/<slug:slug>/', views.blog_details, name='blog_details'),
]

dealsdot/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from dealsdot import settings

from dealsdot.settings import DEBUG




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('info/', include('info.urls', namespace='info')),
]

if DEBUG:
    urlpatterns +=[
        path('__debug__/', include('debug_toolbar.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('search/', views.shop, name='search'),
    path('shop/<slug:subcategory_slug>/', views.shop, name='shop_subcategory'),
    path('product/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

info/urls.py
from django.urls import path
from . import views

app_name = 'info'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('terms/', views.terms, name='terms'),
    path('faq/', views.faq, name='faq'),
   
]

info/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=80, verbose_name='Ім`я')
    email = models.EmailField(max_length=254, verbose_name='Email')
    title = models.TextField(max_length=200, verbose_name='Заголовок')
    comment = models.TextField(max_length=5000, verbose_name='Коментар')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Створено')

    class Meta:
        db_table = 'contact'
        ordering = ['created_at']
        verbose_name = 'Новий коментар'
        verbose_name_plural = 'Нові коментарі'


    def __str__(self):
        return f"{self.name } - {self.title}"
    

class FAQ(models.Model):
    question = models.CharField(max_length=500, verbose_name='Питання')
    answer = models.TextField(max_length=5000, verbose_name='Відповідь')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Створено')

    class Meta:
        db_table = 'faq'
        ordering = ['created_at']
        verbose_name = 'Часті запитання'
        verbose_name_plural = 'Часті запитання'

    def __str__(self):
        return self.question

info/views.py
from django.shortcuts import render

from info.models import Contact, FAQ

# Create your views here.
def contact(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    title = request.POST.get('title')
    comment = request.POST.get('comment')

    if name and email and title and comment:
        Contact.objects.create(
            name=name,
            email=email,
            title=title,
            comment=comment
        )

        return render(request, 'info/contact.html', {'success_message': 'Ваше повідомлення успішно надіслано.'})
    else:
        error_message = "Усі поля обов'язкові для заповнення."
        return render(request, 'info/contact.html', {'error_message': error_message})


def terms(request):
    return render(request, 'info/terms.html')


def faq(request):
    FAQs = FAQ.objects.all()

    context = {
        'FAQs': FAQs
    }

    return render(request, 'info/faq.html', context)

info/templates/info/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="body-content outer-top-ts">
	<div class="container">
    <div class="row">
    
    
      
      <div class="col-md-12"> 
      <div class="contact-page">
			<div class="row">
				<div class="col-md-12 contact-map outer-bottom-vs">
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3886.0080692193424!2d80.29172299999996!3d13.098675000000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a526f446a1c3187%3A0x298011b0b0d14d47!2sTransvelo!5e0!3m2!1sen!2sin!4v1412844527190" width="600" height="450"  style="border:0"></iframe>
				</div>
				<div class="col-md-8 contact-form">
	<div class="col-md-12 contact-title">
		<h4>Контактна форма</h4>
	</div>
	<form class="register-form" role="form" action="{% url "info:contact" %}" method="post">
		{% csrf_token %}
	<div class="col-md-4 ">
			<div class="form-group">
		    <label class="info-title" for="id_name">Ім'я <span>*</span></label>
		    <input type="text" class="form-control text-input" name="name" id="id_name" placeholder="">
		  </div>
		{% comment %} </form> {% endcomment %}
	</div>
	<div class="col-md-4">
		{% comment %} <form class="register-form" role="form"> {% endcomment %}
			<div class="form-group">
		    <label class="info-title" for="id_email">Email <span>*</span></label>
		    <input type="email" class="form-control text-input" name="email" id="id_email" placeholder="">
		  </div>
		{% comment %} </form> {% endcomment %}
	</div>
	<div class="col-md-4">
		{% comment %} <form class="register-form" role="form"> {% endcomment %}
			<div class="form-group">
		    <label class="info-title" for="id_title">Заголовок <span>*</span></label>
		    <input type="text" class="form-control text-input" name="title" id="id_title" placeholder="">
		  </div>
		{% comment %} </form> {% endcomment %}
	</div>
	<div class="col-md-12">
		{% comment %} <form class="register-form" role="form"> {% endcomment %}
			<div class="form-group">
		    <label class="info-title" for="id_comment">Ваше повідомлення <span>*</span></label>
		    <textarea class="form-control unicase-form-control" name="comment" id="id_comment"></textarea>
		  </div>
		</div>
		<div class="col-md-12 outer-bottom-small m-t-20">
			<button type="submit" class="btn-upper btn btn-primary checkout-page-button">ЗАЛИШИТИ ПОВІДОМЛЕННЯ</button>
		</div>
	</form>
</div>
<div class="col-md-4 contact-info">
	<div class="contact-title">
		<h4>Інформація</h4>
	</div>
	<div class="clearfix address">
		<span class="contact-i"><i class="fa fa-map-marker"></i></span>
		<span class="contact-span">ThemesGround, 789 Main rd, Anytown, CA 12345 USA</span>
	</div>
	<div class="clearfix phone-no">
		<span class="contact-i"><i class="fa fa-mobile"></i></span>
		<span class="contact-span">+(888) 123-4567<br>+(888) 456-7890</span>
	</div>
	<div class="clearfix email">
		<span class="contact-i"><i class="fa fa-envelope"></i></span>
		<span class="contact-span"><a href="#">dealdots@gmail.com</a></span>
	</div>
</div>			</div>
</div>
    </div>
    
    

		
</div>
</div>
{% endblock content %}

info/templates/info/faq.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url "index:home" %}">Головна</a></li>
				<li class='active'>FAQ</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div><!-- /.breadcrumb -->
<div class="body-content outer-top-ts">
	<div class="container">
    <div class="row">
<div class="col-md-12">

      <div class="checkout-box faq-page">
			<div class="row">
				<div class="col-md-12">
					<h2 class="heading-title">Часті запитання</h2>
					
					<div class="panel-group checkout-steps" id="accordion">
						<!-- checkout-step-01  -->
						{% for FAQ in FAQs %}
<div class="panel panel-default checkout-step-01">
	<!-- panel-heading -->
	<div class="panel-heading">
		<h4 class="unicase-checkout-title">
			<a data-toggle="collapse" class="collapsed" data-parent="#accordion" href="#collapse{{ FAQ.id }}">
				<span>{{ FAQ.id }}</span>{{ FAQ.question }} 
	        </a>
		</h4>
    </div>
    <!-- panel-heading -->
	
	<div id="collapse{{ FAQ.id }}" class="panel-collapse collapse">
		
		<!-- panel-body  -->
	    <div class="panel-body">
			{{ FAQ.answer }}			
		</div>
		<!-- panel-body  -->
		
	</div><!-- row -->
</div>
{% endfor %}
<!-- checkout-step-01  -->
					    
					  	<!-- checkout-step-09  -->
					  	
					</div><!-- /.checkout-steps -->
				</div>
			</div><!-- /.row -->
		</div>
        
</div>
</div>
</div>
{% endblock content %}

info/templates/info/terms.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url "index:home" %}">Головна</a></li>
				<li class='active'>Умови</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div>
<div class="body-content outer-top-ts">
	<div class="container">
    <div class="row">
<div class="col-md-12">
   
    <div class="terms-conditions-page">
			<div class="row">
				<div class="col-md-12 terms-conditions">
	<h2 class="heading-title">Умови користування</h2>
	<div class="">
		<h3>Угода користувача</h3>
		<ol>
			<p>Викладений нижче текст Угоди користувача (надалі – «Угода» та/або «Угода»), адресований невизначеному колу осіб, відвідувачам сайту: dealsdot (надалі – «Сайт») та/або мобільного додатку dealsdot (надалі – «Мобільний додаток») та/або інших сервісів (надалі разом іменуються як «Он-лайн платформа dealsdot» та/або «Он-лайн платформа»), при використанні, замовленні, листуванні, телефонній розмові, залишенні відгуків тощо на Он-лайн платформі dealsdot. </p>
			<p>Ця Угода є публічною офертою в розумінні положень чинного законодавства України. Вчинення конклюдентних дій особами (далі іменовані «Користувач»/ «Покупець», а в множині «Користувачі»/ «Покупці»), спрямованих на користування Он-лайн платформою dealsdot вважається безумовним прийняттям (акцептом) усіх положень цієї Угоди. Користувач цим визнає, що акцепт Угоди рівносильний підписанню та укладенню Угоди на умовах, викладених в цій Угоді. У випадку визнання недійсною або нездійсненною будь-якої частини даної Угоди користувача, інші її частини будуть залишатися чинними.</p>
			<p>Угода користувача визначає загальні умови створення особистого кабінету користувача, формування та прийняття замовлення до виконання, доставку та повернення товару, маркетингові аспекти взаємодії Користувача та Он-лайн платформи dealsdot тощо.</p>
			<p>Якщо Ви, як Користувач, не погоджуєтесь із цією Угодою користувача, Ви не повинні користуватися Он-лайн платформою dealsdot. Будь ласка, періодично перевіряйте цю Угоду, оскільки зміни в Угоді вказують на те, що Ви приймаєте їх з моменту внесення таких змін.</p>
			<p>Користувач акцептом цієї Угоди надає згоду на обробку та захист своїх персональних даних, в обсязі, порядку, відповідно до мети та цілей обробки згідно з Положенням про обробку персональних даних (надалі – «Положення» та/або «Положення про обробку і захист персональних даних»).</p>
			<p>Ми цінуємо право Користувача на особисте життя та нерозголошення його персональної інформації. Ця Угода користувача — правило, яким користуються всі Користувачі нашого сервісу, та регламентує збір і використання особистої інформації, яка може бути запитана/отримана при відвідуванні Он-лайн платформи при замовленні, листуванні, телефонній розмові, будь-якій іншій комунікації, при якій здійснюється обмін даними/інформацією. Якщо у Користувача виникнуть питання або проблеми у зв’язку з конфіденційністю, Користувач має бажання відкликати Згоду на використання персональних даних, для цього достатньо надіслати повідомлення електронною поштою, з поміткою в темі листа «Персональні дані» на електронну адресу.</p>
		</ol>
		<h3>КОНТАКТ З ОН-ЛАЙН ПЛАТФОРМОЮ</h3>
		<ol>
			<p>Зв'язок з Он-лайн платформою можливий: </p>
			<li>в електронному вигляді за адресою: sales@dealsdot.com.ua</li>
			<li>за допомогою онлайн-чату, доступного на веб-сайті dealsdot.com.ua</li>
			<li>Запити Користувачів у формі електронної пошти або через онлайн-чат можна надсилати цілодобово, однак обробка таких запитів відбувається в робочі дні.</li>
		</ol>
		<h3>ПЕРСОНАЛЬНІ ДАНІ КОРИСТУВАЧА</h3>
		<ol>
			<p>Он-лайн платформа dealsdot, в разі, коли Користувач робить замовлення, берете участь в акціях, дослідженнях або іншим чином взаємодієте з Он-лайн платформою, Он-лайн платформа збирає як особисту інформацію, так і загальні дані.</p>
			<p>Особиста інформація стосується окремого користувача та обробляється в порядку, межах, з метою, визначених в Положенні про обробку персональних даних Користувача (далі – Положення). При цьому не вимагається реєстрація або надання такої інформації для перегляду Он-лайн платформи та отримання доступу до його змісту.</p>
			<p>Для того щоб зробити замовлення товарів/послуг, брати участь в акціях, дослідженнях або іншим чином взаємодіяти з Он-лайн платформою, ви повинні уважно ознайомитися з вашими правами та обов’язками щодо обробки персональних даних, які зазначені в ст. 8 Законі України «Про захист персональних даних» та Положенні, уважно ознайомитися з даною Угодою користувача та Положенням, а також висловити свою повну згоду з їх умовами.</p>
			<p>Якщо ви не погоджуєтеся з будь-якою з умов даної Угоди користувача та Положення про обробку і захист персональних даних, будь ласка, не надавайте особисту інформацію (персональні дані).</p>
		</ol>
		<h3>ОБРОБКА ПЕРСОНАЛЬНИХ ДАНИХ З МЕТОЮ ПРИДБАВАННЯ ТОВАРУ В КРЕДИТ</h3>
		<ol>
			<p>У доповнення до Положення про обробку і захист персональних даних, на виконання вимог Закону України "Про захист персональних даних" шляхом заповнення на Онлайн-платформі заявки для розгляду можливості придбання товару в кредит та натискання кнопки «Замовлення підтверджую» Користувач надає згоду на обробку вказаних у заявці персональних даних наступними особами: АТ «ПУМБ» (код ЄДРПОУ - 14282829), АТ «ОТП БAНК» (код ЄДРПОУ– 21685166), АТ "УКРСИББАНК" (код ЄДРПОУ– 09807750), ТОВ "ФК"ЦФР" (код ЄДРПОУ– 35725063), АТ "АЛЬФА-БАНК" (код ЄДРПОУ– 23494714), АТ КБ «ПРИВАТБАНК» (код ЄДРПОУ – 14360570), АТ "УНІВЕРСАЛ БАНК" (код ЄДРПОУ – 21133352), та іншим фінансовим установам, що надають можливість кредитування на Он-лайн платформі dealsdot, з метою забезпечення реалізації цивільно-правових відносин, надання/отримання та здійснення розрахунків за придбані товари/послуги, в тому числі шляхом кредитування. </p>
			<p>Цією Угодою Користувач не заперечує щодо перевірки переліченими у цій Угоді фінансовими установами інформації у будь-яких бюро кредитних історій України з метою з’ясування відомостей, які стосуються виконання мною взятих на себе зобов’язань по договорам (в т.ч. кредитним), у випадку наявності таких, тим самим розуміючи, що об’єм інформації, яка буде перевірятися, може включати в себе інформацію, яка стосується банківської таємниці, і з’ясування якої буде такою, яка буде повною та достатньою для розуміння його соціального, майнового стану, платоспроможності та несення можливої подальшої майнової відповідальності, у випадку її необхідності.</p>
			<p>Користувач також погоджується з тим, що Володілець має право надавати доступ та передавати його персональні дані третім особам без будь-яких додаткових повідомлень, не змінюючи при цьому мети їх обробки, визначеної в Положенні та цій Угоді. В тому числі, на перевірку зазначеної Користувачем інформації та не заперечує про передачу для можливого необхідного з'ясування даної інформації третім особам, під якими розумію: фінансові установи, колекторські компанії, оператори мобільного та поштового зв’язку, інші фізичні та/або юридичні особи.</p>
			<p>Користувач надає згоду запитувати та отримувати в бюро кредитних історій, включених до Єдиного реєстру бюро кредитних історій (надалі – «Бюро»), дані та інформацію у вигляді зведених показників, сформованих на основі інформації, що міститься у його кредитній історії та/або на основі інформації доступної з відкритих джерел, від третіх осіб, з використанням доступних Бюро моделей розрахунку, а також на використання зазначеної інформації володільцем та/або третіми особами для визначення та пропонування мені Володільцем в особистому кабінеті на Он-лайн платформі dealsdot https://dealsdot.com.ua/ маркетингових/спеціальних пропозицій(фінансових лімітів) для придбання товарів та/або послуг.</p>
		</ol>
		<h3>ТРЕТІ СТОРОНИ, ЯКІ НАДАЮТЬ ПОСЛУГИ</h3>
		<ol>
			<p>Для виконання та доставки замовлень, надання підтримки споживачів, аналізу даних та інших послуг Користувач надає згоду Он-лайн платформі залучати послуги третіх сторін. Передання персональних даних Користувача для обробки третіми особами здійснюється в межах та на умовах, визначених цією Угодою та в Положенні про обробку і захист персональних даних. </p>
			
		</ol>
		<h3>РОЗГОЛОШЕННЯ ТА ПЕРЕДАННЯ ІНФОРМАЦІЇ</h3>
		<ol>
			<p>Інформація про умови розкриття інформації про персональні дані третім особам міститься в Положенні про обробку персональних даних Користувача. </p>
	
		</ol>
		
	</div>
</div>			</div><!-- /.row -->
		</div>
</div>
</div>
</div>
{% endblock content %}