blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('search/', views.blog, name='search'),
    path('', views.blog, name='blog'),
    path('blog_details/<slug:slug>/', views.blog_details, name='blog_details'),
]

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/<slug:product_slug>', views.cart_add, name='cart_add'),
    path('cart_change/<slug:product_slug>', views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>', views.cart_remove, name='cart_remove'),    
    path('user_cart', views.users_cart, name='user_cart'),
    path('cart_update_quantity/<int:cart_id>/<str:action>/', views.cart_update_quantity, name='cart_update_quantity'),
    path('create_order', views.create_order, name='create_order'),
]

dealsdot/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from dealsdot import settings

from dealsdot.settings import DEBUG




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('info/', include('info.urls', namespace='info')),
]

if DEBUG:
    urlpatterns +=[
        path('__debug__/', include('debug_toolbar.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('search/', views.shop, name='search'),
    path('shop/<slug:subcategory_slug>/', views.shop, name='shop_subcategory'),
    path('product/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

carts/models.py
from django.db import models

from index.models import Products
from users.models import User


class CartQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:   
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Користувач")
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Кількість')
    session_key = models.CharField(max_length=32, blank=True, null=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата оновлення')

    class Meta:
        db_table = 'carts'
        verbose_name = 'Корзину'
        verbose_name_plural = 'Корзини'

    objects = CartQueryset().as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)
        

    def __str__(self):
        if self.user:
            return f"Cart for {self.user.username} with {self.product.name}"
        return f"Cart for session {self.session_key} with {self.product.name}"


class Order(models.Model):

    user = models.ForeignKey("users.User", on_delete=models.CASCADE, verbose_name="Користувач")
    carts = models.ManyToManyField(Cart, verbose_name="Замовлення")
    city = models.CharField(max_length=50, verbose_name="Місто")
    address = models.CharField(max_length=150, verbose_name="Адреса") 
    postal_code = models.CharField(max_length=10, verbose_name="Поштовий індекс")
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")

    class Meta:
        db_table = 'order'
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

    def __str__(self):
        return f"Замовлення {self.user.username} | №{self.id} | Дата створення: {self.create_at}"
    

carts/forms.py
from django import forms
from .models import Order



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['city', 'address', 'postal_code']  # Поля, которые будут запрашиваться у пользователя
        labels = {
            'city': 'Місто',
            'address': 'Адреса',
            'postal_code': 'Поштовий індекс',
        }

carts/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.template.loader import render_to_string
from carts.forms import OrderForm
from carts.utils import get_user_carts
from django.contrib.auth.decorators import login_required

from django.views.decorators.http import require_POST
from carts.models import Cart, Order
from index.models import Products





def cart_add(request, product_slug):
    
    product = Products.objects.get(slug=product_slug)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)

    else:
        carts = Cart.objects.filter(
            session_key=request.session.session_key, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(
                session_key=request.session.session_key, product=product, quantity=1)
    
    print(f"Session Key: {request.session.session_key}") # Проверка на сессию

    return redirect(request.META['HTTP_REFERER'])
            
            

def cart_change(request, product_slug):
    ...

def cart_remove(request, cart_id):


    cart = Cart.objects.get(id=cart_id)
    cart.delete()

    return redirect(request.META['HTTP_REFERER'])


def cart_update_quantity(request, cart_id, action):
    # Получаем объект корзины по ID
    cart = get_object_or_404(Cart, id=cart_id)

    if action == 'plus':
        cart.quantity += 1  # Увеличиваем количество на 1
    elif action == 'minus' and cart.quantity > 1:
        cart.quantity -= 1  # Уменьшаем количество на 1, но не ниже 1

    cart.save()  # Сохраняем изменения
    return redirect(request.META.get('HTTP_REFERER', 'index:home'))
   

def users_cart(request):
    carts = get_user_carts(request)  # Получаем корзину
    print(f"Anonymous user, session key: {request.session.session_key}, carts count: {carts.count()}")  # Для отладки

    context = {
        'carts': carts,   
    }
    return render(request, 'carts/user_cart.html', context)

@login_required
def create_order(request):
    # Получаем корзину текущего пользователя
    cart_items = get_user_carts(request)

    if not cart_items.exists():
        return redirect('carts:user_cart')  # Перенаправляем на страницу корзины, если корзина пуста

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            # Создаем заказ
            order = Order.objects.create(
                user=request.user,
                city=form.cleaned_data['city'],
                address=form.cleaned_data['address'],
                postal_code=form.cleaned_data['postal_code']
            )

            # Связываем все элементы корзины с этим заказом
            for item in cart_items:
                order.carts.add(item)  # Сохраняем корзины в ManyToManyField

            # Очищаем корзину
            cart_items.delete()
            
            messages.success(request, 'Ваше замовлення було успішно створено!')

            return redirect('carts:user_cart')
            # return JsonResponse({'success': True, 'message': 'Ваше замовлення було успішно створено!'})

    else:
        form = OrderForm()

    context = {
        'form': form,
        'cart_items': cart_items,  # Отображение корзины пользователя
    }
    return render(request, 'orders/create_order.html', context)

carts/templates/carts/user_cart.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}


{% block content %}
{% comment %} {% user_carts request as carts %} {% endcomment %}
<div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url "index:home" %}">Головна</a></li>
				<li class='active'>Кошик</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div>
<div class="body-content outer-top-ts">
	<div class="container">
		
		
		<div class="row ">
			
			<div class="col-md-12">
				<!-- /.breadcrumb --> 
				<div class="shopping-cart">
					<div class="shopping-cart-table ">
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th class="cart-romove item">Видалити</th>
										<th class="cart-description item">Зображення</th>
										<th class="cart-product-name item">Назва</th>
										{% comment %} <th class="cart-edit item">Edit</th> {% endcomment %}
										<th class="cart-qty item">Кількість</th>
										<th class="cart-sub-total item">Вартість</th>
										<th class="cart-total last-item">Всього</th>
									</tr>
								</thead><!-- /thead -->
								
								<tbody>
									
				{% for cart in carts  %}
				<tr>
					<td class="romove-item"><a href="{% url "carts:cart_remove" cart.id %}" title="cancel" class="icon"><i class="fa fa-trash-o"></i></a></td>
					<td class="cart-image">
						<a class="entry-thumbnail" href="{% url "index:product_detail" cart.product.slug %}">
						    <img src="{{ cart.product.image.url }}" alt="{{ cart.product.name }}">
						</a>
					</td>
					<td class="cart-product-name-info">
						<h4 class='cart-product-description'><a href="{% url "index:product_detail" cart.product.slug %}">{{ cart.product.name }}</a></h4>
						<div class="row">
							<div class="col-sm-12">
								<div class="rating rateit-small"></div>
							</div>
							<div class="col-sm-12">
								<div class="reviews">
									(06 Reviews)
								</div>
							</div>
						</div><!-- /.row -->
						
					</td>
					{% comment %} <td class="cart-product-edit"><a href="#" class="product-edit">Edit</a></td> {% endcomment %}
					{% comment %} <td class="cart-product-quantity">
						<div class="quant-input">
				                <div class="arrows">
				                  <div class="arrow plus gradient"><span class="ir"><i class="icon fa fa-sort-asc"></i></span></div>
				                  <div class="arrow minus gradient"><span class="ir"><i class="icon fa fa-sort-desc"></i></span></div>
				                </div>
				                <input type="text" value="{{ cart.quantity }}">
			              </div>
		            </td> {% endcomment %}

					<td class="cart-product-quantity">
						<div class="quant-input">
							<div class="arrows">
								<!-- Увеличение количества -->
								<a href="{% url 'carts:cart_update_quantity' cart.id 'plus' %}" class="arrow plus gradient">
									<span class="ir"><i class="icon fa fa-sort-asc"></i></span>
								</a>
					
								<!-- Уменьшение количества -->
								<a href="{% url 'carts:cart_update_quantity' cart.id 'minus' %}" class="arrow minus gradient">
									<span class="ir"><i class="icon fa fa-sort-desc"></i></span>
								</a>
							</div>
							<input type="text" value="{{ cart.quantity }}">
						</div>
					</td>

					<td class="cart-product-sub-total"><span class="cart-sub-total-price">${{ cart.product.sell_price }}</span></td>
					<td class="cart-product-grand-total">
						<span class="cart-grand-total-price">
						${{ cart.product.sell_price|multiply:cart.quantity }}
					</span>
					</td> 
					

				</tr>
				{% endfor %}

				
			</tbody><!-- /tbody -->
            
            <tfoot>
				<tr>
					<td colspan="7">
						<div class="shopping-cart-btn">
							<span class="">
								<a href="{% url "index:shop" %}" class="btn btn-upper btn-primary outer-left-xs">Повернутись до покупок</a>
								{% comment %} <a href="#" class="btn btn-upper btn-primary pull-right outer-right-xs">Update shopping cart</a> {% endcomment %}
							</span>
						</div><!-- /.shopping-cart-btn -->
					</td>
				</tr>
			</tfoot>
		</table><!-- /table -->
	</div>
</div><!-- /.shopping-cart-table -->				<div class="col-md-4 col-sm-12 estimate-ship-tax">
	<table class="table">
		<thead>
			<tr>
				<th>
					<span class="estimate-title">Заповніть адресу</span>
					{% comment %} <p>Enter your destination to get shipping and tax.</p> {% endcomment %}
				</th>
			</tr>
		</thead><!-- /thead -->
		<tbody>
				<tr>
					<td>
						<form action="{% url "carts:create_order" %}" method="post">
								{% csrf_token %}
							<div class="form-group">
								<label class="info-title control-label" for="id_city">Місто <span>*</span></label>
								<input type="text" class="form-control unicase-form-control text-input" name="city" id="id_city" placeholder="">
								
							</div>
							<div class="form-group">
								<label class="info-title control-label" for="id_address">Адреса <span>*</span></label>
								<input type="text" class="form-control unicase-form-control text-input" name="address" id="id_address" placeholder="">
								
							</div>
							<div class="form-group">
								<label class="info-title control-label" for="id_postal_code">Поштовий код</label>
								<input type="text" class="form-control unicase-form-control text-input" name="postal_code" id="id_postal_code" placeholder="">
							</div>
							<div class="pull-right">
								{% if messages %}
									<ul class="messages">
										{% for message in messages %}
											<li class="alert alert-{{ message.tags }}">{{ message }}</li>
										{% endfor %}
									</ul>
								{% endif %}
								<button type="submit" class="btn-upper btn btn-primary">ЗРОБИТИ ЗАМОВЛЕННЯ</button>
							</div>
						</form>
						
					</td>
				</tr>
		</tbody>
	</table>
</div><!-- /.estimate-ship-tax -->

{% comment %} <div class="col-md-4 col-sm-12 estimate-ship-tax">
	<table class="table">
		<thead>
			<tr>
				<th>
					<span class="estimate-title">Discount Code</span>
					<p>Enter your coupon code if you have one..</p>
				</th>
			</tr>
		</thead>
		<tbody>
				<tr>
					<td>
						<div class="form-group">
							<input type="text" class="form-control unicase-form-control text-input" placeholder="You Coupon..">
						</div>
						<div class="clearfix pull-right">
							<button type="submit" class="btn-upper btn btn-primary">APPLY COUPON</button>
						</div>
					</td>
				</tr>
		</tbody><!-- /tbody -->
	</table><!-- /table -->
</div><!-- /.estimate-ship-tax --> {% endcomment %}

<div class="col-md-4 col-sm-12 cart-shopping-total">
	<table class="table">
		<thead>
			<tr>
				<th>
					<div class="cart-sub-total">
						Всього:<span class="inner-left-md">${{ carts.total_price }}</span>
					</div>
					{% comment %} <div class="cart-grand-total">
						Grand Total<span class="inner-left-md">${{ carts.total_price }}</span>
					</div> {% endcomment %}
				</th>
			</tr>
		</thead><!-- /thead -->
		{% comment %} <tbody>
				<tr>
					<td>
						<div class="cart-checkout-btn pull-right">
							<button type="submit" class="btn btn-primary checkout-btn">PROCCED TO CHEKOUT</button>
							<span class="">Checkout with multiples address!</span>
						</div>
					</td>
				</tr>
		</tbody><!-- /tbody --> {% endcomment %}
	</table><!-- /table -->
</div><!-- /.cart-shopping-total -->			</div><!-- /.shopping-cart -->
</div>
</div>
</div>

{% endblock content %}