blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('search/', views.blog, name='search'),
    path('', views.blog, name='blog'),
    path('blog_details/<slug:slug>/', views.blog_details, name='blog_details'),
]

dealsdot/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from dealsdot import settings

from dealsdot.settings import DEBUG




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('info/', include('info.urls', namespace='info')),
]

if DEBUG:
    urlpatterns +=[
        path('__debug__/', include('debug_toolbar.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('search/', views.shop, name='search'),
    path('shop/<slug:subcategory_slug>/', views.shop, name='shop_subcategory'),
    path('product/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200, unique=True)
    content = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='blog/', blank=True, null=True)
    slug = models.SlugField(max_length=200, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='blog_posts')

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Новий пост'
        verbose_name_plural = 'Нові пости'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    

class BlogComment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=80, verbose_name='Ім`я')
    email = models.EmailField(max_length=254, verbose_name='Email')
    title = models.TextField(max_length=200, verbose_name='Заголовок')
    comment = models.TextField(max_length=5000, verbose_name='Коментар')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Створено')
    

    class Meta:
        db_table = 'blog_comment'
        ordering = ['created_at']
        verbose_name = 'Новий коментар'
        verbose_name_plural = 'Нові коментарі'

    def __str__(self):
        return 'Comment {} by {}'.format(self.title, self.name)

blog/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404


from blog.models import Blog, BlogComment


# Create your views here.
def blog(request):
    page = request.GET.get('page', 1)
    query = request.GET.get('q', None)
    
    if query:
        # Если есть поисковый запрос, фильтруем посты по полям заголовка или содержимого
        posts = Blog.objects.filter(
            Q(title__icontains=query) | Q(content__icontains=query)
        ).order_by('-created_at')
        
    else:
        # Если запроса нет, показываем все посты
        posts = Blog.objects.order_by('-created_at')
        
    
    paginator = Paginator(posts, 6)  
    current_page = paginator.page(int(page))

    context = {
        'posts': current_page,
        'query': query,
        
    }
    return render(request, 'blog/blog.html', context)

def blog_details(request, slug):
    
    post = get_object_or_404(Blog, slug=slug)
    comments = BlogComment.objects.filter(blog=post)
    comment_count = comments.count()
    
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        title = request.POST.get('title')
        comment_text = request.POST.get('comment')
        
        # Валидация полей
        if name and email and title and comment_text:
            BlogComment.objects.create(
                blog=post,
                name=name,
                email=email,
                title=title,
                comment=comment_text
            )
            return redirect('blog:blog_details', slug=slug)
        else:
            # Обработка ошибки, если данные не заполнены
            error_message = "Усі поля обов'язкові для заповнення."
            context = {
                'post': post,
                'comments': comments,
                'error_message': error_message
            }
            return render(request, 'blog/blog_details.html', context)

    context = {
        'post': post,  
        'comments': comments, 
        'comment_count': comment_count, 
    }
    return render(request, 'blog/blog_details.html', context)

    

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="breadcrumb">
    <div class="container">
            <div class="breadcrumb-inner">
                <ul class="list-inline list-unstyled">
                    <li><a href="{% url "index:home" %}">Головна</a></li>
                    <li class="active">Блог</li>
                </ul>
            </div><!-- /.breadcrumb-inner -->
            </div>
        </div>
    <div class="body-content blog-page outer-top-ts">
        <div class="container">
            <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-9"> 
            <!-- /.container -->
    
                    <div>
                        <div class="blog-post">
                            {% for post in posts %}
                            <div class="post-image">
                                <a href="{% url "blog:blog_details" post.slug %}"><img class="img-responsive" src="{{ post.image.url }}" alt="{{ post.title }}"></a>
                            </div>
                            <h1><a href="{% url "blog:blog_details" post.slug %}">{{ post.title }}</a></h1>
                            <span class="author">{{ post.autor }}</span>
                            <span class="review">Коментарів: {{ post.blogcomment_set.count }}</span>
                            <span class="date-time">{{ post.created_at|date:"d.m.Y" }}</span>
                            <p>{{ post.content |truncatechars:500 }}</p>
                            <a href="{% url "blog:blog_details" post.slug %}" class="btn btn-upper btn-primary read-more">Читати далі</a>
                            {% endfor %}
    </div>
    
    
    <div class="clearfix blog-pagination filters-container  wow fadeInUp" style="padding:0px; background:none; box-shadow:none; margin-top:15px; border:none">
                            
        <div class="text-right">
             <div class="pagination-container">
        <ul class="list-inline list-unstyled">
            <li class="prev">
                <a href="{% if posts.has_previous %}?page={{posts.previous_page_number}}{% else %}#{% endif %}"><i class="fa fa-angle-left"></i></a>
            </li>
            
            {% for page in posts.paginator.page_range %}
            {% if page >= posts.number|add:-2 and page <= posts.number|add:2 %}
            <li class="page-item {% if posts.number == page %} active {% endif %}">
                <a href="?page={{page}}">{{ page }}</a>
            </li>	
            {% endif %}
            {% endfor %}
           
            
            <li class="next">
                <a href="{% if posts.has_next %}?page={{posts.next_page_number}}{% else %}#{% endif %}"><i class="fa fa-angle-right"></i></a>
            </li>
        </ul><!-- /.list-inline -->
    </div><!-- /.pagination-container -->    </div><!-- /.text-right -->
    
    </div><!-- /.filters-container -->			
    
    
      
    
    
        </div>
                    
                </div>
                
                
                <div class="col-xs-12 col-sm-12 col-md-3 sidebar">
                <div class="sidebar-module-container">
                            <div class="search-area outer-bottom-small">
        <form action="{% url "blog:search" %}" mathod="get">
            <div class="control-group" style="position: relative;">
                <input placeholder="Пошук по блогу" name="q" class="search-field" style="padding-right: 40px;"> <!-- Добавляем отступ для кнопки -->
                <button type="submit" class="search-button" style="position: absolute;  top: 50%; transform: translateY(-1200%); border: none; background: none;">
                    {% comment %} <i class="fa fa-search"></i> <!-- Иконка поиска --> {% endcomment %}
                </button>
            </div> 
        </form>
    </div>		
    
    <div class="home-banner outer-top-n outer-bottom-xs">
    <img src="{% static "images/banners/LHS-banner.jpg" %}" alt="Image">
    </div>
                    <!-- ==============================================CATEGORY============================================== -->
    {% comment %} <div class="sidebar-widget outer-bottom-xs">
        <h3 class="section-title">Category</h3>
        <div class="sidebar-widget-body m-t-10">
            <div class="accordion">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a href="#collapseOne" data-toggle="collapse" class="accordion-toggle collapsed">
                           Camera
                        </a>
                    </div><!-- /.accordion-heading -->
                    <div class="accordion-body collapse" id="collapseOne" style="height: 0px;">
                        <div class="accordion-inner">
                            <ul>
                                <li><a href="#">gaming</a></li>
                                <li><a href="#">office</a></li>
                                <li><a href="#">kids</a></li>
                                <li><a href="#">for women</a></li>
                            </ul>
                        </div><!-- /.accordion-inner -->
                    </div><!-- /.accordion-body -->
                </div><!-- /.accordion-group -->
    
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a href="#collapseTwo" data-toggle="collapse" class="accordion-toggle collapsed">
                          Desktops
                        </a>
                    </div><!-- /.accordion-heading -->
                    <div class="accordion-body collapse" id="collapseTwo" style="height: 0px;">
                        <div class="accordion-inner">
                            <ul>
                                <li><a href="#">gaming</a></li>
                                <li><a href="#">office</a></li>
                                <li><a href="#">kids</a></li>
                                <li><a href="#">for women</a></li>
                            </ul>
                        </div><!-- /.accordion-inner -->
                    </div><!-- /.accordion-body -->
                </div><!-- /.accordion-group -->
    
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a href="#collapseThree" data-toggle="collapse" class="accordion-toggle collapsed">
                           Pants
                        </a>
                    </div><!-- /.accordion-heading -->
                    <div class="accordion-body collapse" id="collapseThree" style="height: 0px;">
                        <div class="accordion-inner">
                            <ul>
                                <li><a href="#">gaming</a></li>
                                <li><a href="#">office</a></li>
                                <li><a href="#">kids</a></li>
                                <li><a href="#">for women</a></li>
                            </ul>
                        </div><!-- /.accordion-inner -->
                    </div><!-- /.accordion-body -->
                </div><!-- /.accordion-group -->
    
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a href="#collapseFour" data-toggle="collapse" class="accordion-toggle collapsed">
                           Bags
                        </a>
                    </div><!-- /.accordion-heading -->
                    <div class="accordion-body collapse" id="collapseFour" style="height: 0px;">
                        <div class="accordion-inner">
                            <ul>
                                <li><a href="#">gaming</a></li>
                                <li><a href="#">office</a></li>
                                <li><a href="#">kids</a></li>
                                <li><a href="#">for women</a></li>
                            </ul>
                        </div><!-- /.accordion-inner -->
                    </div><!-- /.accordion-body -->
                </div><!-- /.accordion-group -->
    
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a href="#collapseFive" data-toggle="collapse" class="accordion-toggle collapsed">
                          Hats
                        </a>
                    </div><!-- /.accordion-heading -->
                    <div class="accordion-body collapse" id="collapseFive" style="height: 0px;">
                        <div class="accordion-inner">
                            <ul>
                                <li><a href="#">gaming</a></li>
                                <li><a href="#">office</a></li>
                                <li><a href="#">kids</a></li>
                                <li><a href="#">for women</a></li>
                            </ul>
                        </div><!-- /.accordion-inner -->
                    </div><!-- /.accordion-body -->
                </div><!-- /.accordion-group -->
    
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a href="#collapseSix" data-toggle="collapse" class="accordion-toggle collapsed">
                         Accessories
                        </a>
                    </div><!-- /.accordion-heading -->
                    <div class="accordion-body collapse" id="collapseSix" style="height: 0px;">
                        <div class="accordion-inner">
                            <ul>
                                <li><a href="#">gaming</a></li>
                                <li><a href="#">office</a></li>
                                <li><a href="#">kids</a></li>
                                <li><a href="#">for women</a></li>
                            </ul>
                        </div><!-- /.accordion-inner -->
                    </div><!-- /.accordion-body -->
                </div><!-- /.accordion-group -->
    
            </div><!-- /.accordion -->
        </div><!-- /.sidebar-widget-body -->
    </div><!-- /.sidebar-widget --> {% endcomment %}
        {% comment %} <!-- ============================================== CATEGORY : END ============================================== -->						<div class="sidebar-widget outer-bottom-xs wow fadeInUp">
        <h3 class="section-title">Tab Widget</h3>
        <ul class="nav nav-tabs">
          <li class="active"><a href="#popular" data-toggle="tab">popular post</a></li>
          <li><a href="#recent" data-toggle="tab">recent post</a></li>
        </ul>
        <div class="tab-content" style="padding-left:0">
           <div class="tab-pane active m-t-20" id="popular">
            <div class="blog-post inner-bottom-30 " >
                <img class="img-responsive" src="assets/images/blog-post/blog_big_01.jpg" alt="">
                <h4><a href="blog-details.html">Powerful and flexible premium Ecommerce themes</a></h4>
                    <span class="review">6 Comments</span>
                <span class="date-time">12/06/19</span>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
                
            </div>
            <div class="blog-post" >
                <img class="img-responsive" src="assets/images/blog-post/blog_big_02.jpg" alt="">
                <h4><a href="blog-details.html">Awesome template with lot's of features on the board!</a></h4>
                <span class="review">6 Comments</span>
                <span class="date-time">23/06/19</span>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
                
            </div>
        </div>
    
        <div class="tab-pane m-t-20" id="recent">
            <div class="blog-post inner-bottom-30" >
                <img class="img-responsive" src="assets/images/blog-post/blog_big_03.jpg" alt="">
                <h4><a href="blog-details.html">Powerful and flexible premium Ecommerce themes</a></h4>
                <span class="review">6 Comments</span>
                <span class="date-time">05/06/19</span>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
                
            </div>
            <div class="blog-post">
                <img class="img-responsive" src="assets/images/blog-post/blog_big_01.jpg" alt="">
                <h4><a href="blog-details.html">Awesome template with lot’s of features on the board!</a></h4>
                <span class="review">6 Comments</span>
                <span class="date-time">10/07/19</span>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
                
            </div>
        </div>
        </div> {% endcomment %}
    </div>
                           
                </div>
             </div>   
                
            </div>
{% endblock content %}

blog/templates/blog/blog_details.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="breadcrumb">
<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url "index:home" %}">Головна</a></li>
				<li class="active">Блог</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div>
    </div>
<div class="body-content blog-page outer-top-ts">
	<div class="container">
		<div class="row">
 <div class="col-xs-12 col-sm-9 col-md-9"> 
        <!-- /.container -->


					<div class="blog-post wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp;">
						<div class="post-image">
							<a href="{% url "blog:blog_details" post.slug %}"><img class="img-responsive" src="{{ post.image.url }}" alt="{{ post.title }}"></a>
						</div>
	<h1>{{ post.title }}</h1>
	<span class="author">{{ post.autor }}</span>
	<span class="review">Коментарів: {{ comment_count }}</span>
	<span class="date-time">{{ post.created_at|date:"d.m.Y" }}</span>
	<p>{{ post.content }}</p>
	
	<div class="social-media">
		<span>share post:</span>
		<a href="#"><i class="fa fa-facebook"></i></a>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-linkedin"></i></a>
		<a href=""><i class="fa fa-rss"></i></a>
		<a href="" class="hidden-xs"><i class="fa fa-pinterest"></i></a>
	</div>
</div>

					<div class="blog-review wow fadeInUp" style="visibility: hidden; animation-name: none; margin-top: 30px;">
	<div class="row">
		<div class="col-md-12 col-xs-12">
			<h3 class="title-review-comments">Коментарів: {{ comment_count }}</h3>
		</div>
		{% for comment in comments %}
		<div class="col-md-2 col-sm-2">
			<img src="{{ comment.user.avatar.url }}" alt="Responsive image" class="img-rounded img-responsive">
		</div>
		<div class="col-md-10 col-sm-10 blog-comments outer-bottom-xs">
			<div class="blog-comments inner-bottom-xs">
				<h4>{{ comment.user.username }}</h4>
				<span class="review-action pull-right">
					{{ comment.created_at|date:"d.m.Y / H:i" }}   
					
				</span>
				<p>{{ comment.comment }}</p>
			</div>
		</div>
		{% endfor %}
		
		
	</div>
</div>					<div class="blog-write-comment outer-bottom-xs outer-top-vs">
	<div class="row">
		<div class="col-md-12">
			<h4>Залиште коментар</h4>
		</div>
			{% if error_message %}
		<div class="alert alert-danger">
			{{ error_message }}
		</div>
			{% endif %}

		<div class="col-md-4">
			<form class="register-form" role="form" action="{% url "blog:blog_details" post.slug %}" method="post">
				{% csrf_token %}
				<div class="form-group">
			    <label class="info-title" for="id_name">Ім'я <span>*</span></label>
			    <input type="text" class="form-control unicase-form-control text-input" name="name" id="id_name" placeholder="">
			  </div>
			</div>
			<div class="col-md-4">
				
					<div class="form-group">
						<label class="info-title" for="id_email">Email<span>*</span></label>
						<input type="email" class="form-control unicase-form-control text-input" name="email" id="id_email" placeholder="">
					</div>
					
				</div>
				<div class="col-md-4">
					
						<div class="form-group">
							<label class="info-title" for="id_title">Заголовок <span>*</span></label>
							<input type="text" class="form-control unicase-form-control text-input" name="title" id="id_title" placeholder="">
						</div>
						
					</div>
					<div class="col-md-12">
						
							<div class="form-group">
								<label class="info-title" for="id_comment">Коментар <span>*</span></label>
								<textarea class="form-control unicase-form-control" name="comment" id="id_comment"></textarea>
							</div>
							
						</div>
						<div class="col-md-12  m-t-20">
							<button type="submit" class="btn-upper btn btn-primary checkout-page-button">Залишити коментар</button>
							
							
							
						</div>
					</form>
        </div>
        </div>
</div>
            
<div class="col-xs-12 col-sm-12 col-md-3 sidebar">
	<div class="sidebar-module-container">
				<div class="search-area outer-bottom-small">
<form action="{% url "blog:search" %}" mathod="get">
<div class="control-group" style="position: relative;">
	<input placeholder="Пошук по блогу" name="q" class="search-field" style="padding-right: 40px;"> <!-- Добавляем отступ для кнопки -->
	<button type="submit" class="search-button" style="position: absolute;  top: 50%; transform: translateY(-1200%); border: none; background: none;">
		{% comment %} <i class="fa fa-search"></i> <!-- Иконка поиска --> {% endcomment %}
	</button>
</div> 
</form>
</div>

<div class="home-banner outer-top-n outer-bottom-xs">
<img src="{% static "images/banners/LHS-banner.jpg" %}" alt="Image">
</div>
				<!-- ==============================================CATEGORY============================================== -->
{% comment %} <div class="sidebar-widget outer-bottom-xs">
	<h3 class="section-title">Category</h3>
	<div class="sidebar-widget-body m-t-10">
		<div class="accordion">
	    	<div class="accordion-group">
	            <div class="accordion-heading">
	                <a href="#collapseOne" data-toggle="collapse" class="accordion-toggle collapsed">
	                   Camera
	                </a>
	            </div><!-- /.accordion-heading -->
	            <div class="accordion-body collapse" id="collapseOne" style="height: 0px;">
	                <div class="accordion-inner">
	                    <ul>
	                        <li><a href="#">gaming</a></li>
	                        <li><a href="#">office</a></li>
	                        <li><a href="#">kids</a></li>
	                        <li><a href="#">for women</a></li>
	                    </ul>
	                </div><!-- /.accordion-inner -->
	            </div><!-- /.accordion-body -->
	        </div><!-- /.accordion-group -->

	        <div class="accordion-group">
	            <div class="accordion-heading">
	                <a href="#collapseTwo" data-toggle="collapse" class="accordion-toggle collapsed">
	                  Desktops
	                </a>
	            </div><!-- /.accordion-heading -->
	            <div class="accordion-body collapse" id="collapseTwo" style="height: 0px;">
	                <div class="accordion-inner">
	                    <ul>
	                        <li><a href="#">gaming</a></li>
	                        <li><a href="#">office</a></li>
	                        <li><a href="#">kids</a></li>
	                        <li><a href="#">for women</a></li>
	                    </ul>
	                </div><!-- /.accordion-inner -->
	            </div><!-- /.accordion-body -->
	        </div><!-- /.accordion-group -->

	        <div class="accordion-group">
	            <div class="accordion-heading">
	                <a href="#collapseThree" data-toggle="collapse" class="accordion-toggle collapsed">
	                   Pants
	                </a>
	            </div><!-- /.accordion-heading -->
	            <div class="accordion-body collapse" id="collapseThree" style="height: 0px;">
	                <div class="accordion-inner">
	                    <ul>
	                        <li><a href="#">gaming</a></li>
	                        <li><a href="#">office</a></li>
	                        <li><a href="#">kids</a></li>
	                        <li><a href="#">for women</a></li>
	                    </ul>
	                </div><!-- /.accordion-inner -->
	            </div><!-- /.accordion-body -->
	        </div><!-- /.accordion-group -->

	        <div class="accordion-group">
	            <div class="accordion-heading">
	                <a href="#collapseFour" data-toggle="collapse" class="accordion-toggle collapsed">
	                   Bags
	                </a>
	            </div><!-- /.accordion-heading -->
	            <div class="accordion-body collapse" id="collapseFour" style="height: 0px;">
	                <div class="accordion-inner">
	                    <ul>
	                        <li><a href="#">gaming</a></li>
	                        <li><a href="#">office</a></li>
	                        <li><a href="#">kids</a></li>
	                        <li><a href="#">for women</a></li>
	                    </ul>
	                </div><!-- /.accordion-inner -->
	            </div><!-- /.accordion-body -->
	        </div><!-- /.accordion-group -->

	        <div class="accordion-group">
	            <div class="accordion-heading">
	                <a href="#collapseFive" data-toggle="collapse" class="accordion-toggle collapsed">
	                  Hats
	                </a>
	            </div><!-- /.accordion-heading -->
	            <div class="accordion-body collapse" id="collapseFive" style="height: 0px;">
	                <div class="accordion-inner">
	                    <ul>
	                        <li><a href="#">gaming</a></li>
	                        <li><a href="#">office</a></li>
	                        <li><a href="#">kids</a></li>
	                        <li><a href="#">for women</a></li>
	                    </ul>
	                </div><!-- /.accordion-inner -->
	            </div><!-- /.accordion-body -->
	        </div><!-- /.accordion-group -->

	        <div class="accordion-group">
	            <div class="accordion-heading">
	                <a href="#collapseSix" data-toggle="collapse" class="accordion-toggle collapsed">
	                 Accessories
	                </a>
	            </div><!-- /.accordion-heading -->
	            <div class="accordion-body collapse" id="collapseSix" style="height: 0px;">
	                <div class="accordion-inner">
	                    <ul>
	                        <li><a href="#">gaming</a></li>
	                        <li><a href="#">office</a></li>
	                        <li><a href="#">kids</a></li>
	                        <li><a href="#">for women</a></li>
	                    </ul>
	                </div><!-- /.accordion-inner -->
	            </div><!-- /.accordion-body -->
	        </div><!-- /.accordion-group -->

	    </div><!-- /.accordion -->
	</div><!-- /.sidebar-widget-body -->
</div><!-- /.sidebar-widget --> {% endcomment %}
	{% comment %} <!-- ============================================== CATEGORY : END ============================================== -->						<div class="sidebar-widget outer-bottom-xs wow fadeInUp">
    <h3 class="section-title">Tab Widget</h3>
	<ul class="nav nav-tabs">
	  <li class="active"><a href="#popular" data-toggle="tab">popular post</a></li>
	  <li><a href="#recent" data-toggle="tab">recent post</a></li>
	</ul>
	<div class="tab-content" style="padding-left:0">
	   <div class="tab-pane active m-t-20" id="popular">
		<div class="blog-post inner-bottom-30 " >
			<img class="img-responsive" src="{% static "images/blog-post/blog_big_01.jpg" %}" alt="">
			<h4><a href="blog-details.html">Simple Blog Post</a></h4>
				<span class="review">6 Comments</span>
			<span class="date-time">12/06/16</span>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
			
		</div>
		<div class="blog-post" >
			<img class="img-responsive" src="assets/images/blog-post/blog_big_02.jpg" alt="">
			<h4><a href="blog-details.html">Simple Blog Post</a></h4>
			<span class="review">6 Comments</span>
			<span class="date-time">23/06/16</span>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
			
		</div>
	</div>

	<div class="tab-pane m-t-20" id="recent">
		<div class="blog-post inner-bottom-30" >
			<img class="img-responsive" src="assets/images/blog-post/blog_big_03.jpg" alt="">
			<h4><a href="blog-details.html">Simple Blog Post</a></h4>
			<span class="review">6 Comments</span>
			<span class="date-time">5/06/16</span>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
			
		</div>
		<div class="blog-post">
			<img class="img-responsive" src="assets/images/blog-post/blog_big_01.jpg" alt="">
			<h4><a href="blog-details.html">Simple Blog Post</a></h4>
			<span class="review">6 Comments</span>
			<span class="date-time">10/07/16</span>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
			
		</div>
	</div>
	</div>
</div> {% endcomment %}
		
            </div>
            
       </div>
       </div>
       </div>   
{% endblock content %}