blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('search/', views.blog, name='search'),
    path('', views.blog, name='blog'),
    path('blog_details/<slug:slug>/', views.blog_details, name='blog_details'),
]

dealsdot/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from dealsdot import settings

from dealsdot.settings import DEBUG




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('info/', include('info.urls', namespace='info')),
]

if DEBUG:
    urlpatterns +=[
        path('__debug__/', include('debug_toolbar.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('search/', views.shop, name='search'),
    path('shop/<slug:subcategory_slug>/', views.shop, name='shop_subcategory'),
    path('product/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.sign_in, name='login'),
    path('registration', views.sign_up, name='registration'),
    path('logout/', views.logout, name='logout'),
    
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True, verbose_name='Номер телефону')
    avatar = models.ImageField(upload_to='user/', blank=True, null=True)

    class Meta:
        db_table = 'user'
        verbose_name = 'Користувач'
        verbose_name_plural = 'Користувачі'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class UserLoginForm(forms.Form):
    email = forms.EmailField(label='Email Address')
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = (
            'email',
            'username', 
            'phone', 
            'password1', 
            'password2',
        )

    email = forms.CharField()
    username = forms.CharField()
    phone = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth import authenticate, login
from carts.models import Cart
from users.models import User

from users.forms import UserLoginForm, UserRegistrationForm

# # Create your views here.


def sign_in(request):

    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            
            session_key = request.session.session_key

            # Попробуем найти пользователя по email
            try:
                user = User.objects.get(email=email)
                # Аутентификация по username, так как Django требует username для authenticate
                user = authenticate(username=user.username, password=password)
            except User.DoesNotExist:
                user = None
            
            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index:home'))
            else:
                form.add_error(None, "Invalid email or password")
    else:
        form = UserLoginForm()

    context = {
        'title': 'Sign In',
        'form': form,
    }
    return render(request, 'users/sign_in.html', context)

def sign_up(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            return HttpResponseRedirect(reverse('index:home'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Sign Up',
        'form': form,
    }
    return render(request, 'users/sign_up.html', context)


@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Ви вийшли з аккаунту")
    auth.logout(request)
    return redirect(reverse('users:login'))
    

users/templates/users/sign_in.html
{% extends "base.html" %}
{% load static %}

{% block content %}
      <div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url "index:home" %}">Головна</a></li>
				<li class='active'>Авторизація</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div><!-- /.breadcrumb -->
<div class="body-content outer-top-ts">
	<div class="container">
    <div class="row">
<div class="col-md-12"> 

      <div class="sign-in-page">
			<div class="row">
				<!-- Sign-in -->			
<div class="col-md-6 col-sm-6 sign-in">
	<h4 class="">Авторизація</h4>
	<p class="">Ласкаво просиво в ваш аккаунт.</p>
	<div class="social-sign-in outer-top-xs">
		<a href="#" class="facebook-sign-in"><i class="fa fa-facebook"></i> Sign In with Facebook</a>
		<a href="#" class="twitter-sign-in"><i class="fa fa-twitter"></i> Sign In with Twitter</a>
	</div>
	<form class="register-form outer-top-xs" method="post" role="form" action="{% url "users:login" %}">
		{% csrf_token %}
		
		<div class="form-group">
		    <label class="info-title" for="id_email">Email <span>*</span></label>
		    <input type="email" class="form-control unicase-form-control text-input" name="email" id="id_email" >
		</div>
		<div class="form-group">
		    <label class="info-title" for="id_password">Пароль <span>*</span></label>
		    <input type="password" class="form-control unicase-form-control text-input" name="password" id="id_password" >
		</div>
		<div class="radio outer-xs">
		  	<label>
		    	{% comment %} <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">Remember me! {% endcomment %}
		  	</label>
		  	<a href="#" class="forgot-password pull-right">Відновити пароль?</a>
		</div>
	  	<button type="submit" class="btn-upper btn btn-primary checkout-page-button">Вхід</button> 
	</form>					
</div>
<!-- Sign-in -->

			</div><!-- /.row -->
		</div>
        
        </div>
        </div>
        </div>
       
{% endblock content %}

users/templates/users/sign_up.html
{% extends "base.html" %}
{% load static %}

{% block content %}
      <div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url "index:home" %}">Головна</a></li>
				<li class='active'>Реєстрація</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div><!-- /.breadcrumb -->
<div class="body-content outer-top-ts">
	<div class="container">
    <div class="row">
<div class="col-md-12"> 

      <div class="sign-in-page">
			<div class="row">
				

<!-- create a new account -->
<div class="col-md-6 col-sm-6 create-new-account">
	<h4 class="checkout-subtitle">Створити новий обліковий запис</h4>
	<p class="text title-tag-line">Створити ваш новий аккаунт.</p>
	<form class="register-form outer-top-xs" role="form" action="{% url "users:registration" %}" method="post">
		{% csrf_token %}
		<div class="form-group">
	    	<label class="info-title" for="id_email">Email <span>*</span></label>
	    	<input type="email" class="form-control unicase-form-control text-input" id="id_email" 
			value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
			name="email">
			{% if forms.email.errors %}
			<div class="alert alert-danger alert-dismissible fade show">{{forms.email.errors}}</div>
			{% endif %}
	  	</div>
        <div class="form-group">
		    <label class="info-title" for="id_username">Username <span>*</span></label>
		    <input type="text" class="form-control unicase-form-control text-input" id="id_username" 
			value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
			name="username">
			{% if forms.username.errors %}
			<div class="alert alert-danger alert-dismissible fade show">{{forms.username.errors}}</div>
			{% endif %}
			
		</div>
        <div class="form-group">
		    <label class="info-title" for="id_phone">Телефонний номер <span>*</span></label>
		    <input type="text" class="form-control unicase-form-control text-input" id="id_phone" 
			value="{% if form.phone.value %}{{ form.phone.value }}{% endif %}"
			name="phone">
			{% if forms.phone.errors %}
			<div class="alert alert-danger alert-dismissible fade show">{{forms.phone.errors}}</div>
			{% endif %}
		</div>
        <div class="form-group">
		    <label class="info-title" for="id_password1">Пароль <span>*</span></label>
		    <input type="password" class="form-control unicase-form-control text-input" id="id_password1" 
			value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
			name="password1">
			{% if forms.password1.errors %}
			<div class="alert alert-danger alert-dismissible fade show">{{forms.password1.errors}}</div>
			{% endif %}
		</div>
         <div class="form-group">
		    <label class="info-title" for="id_password2">Повторити пароль <span>*</span></label>
		    <input type="password" class="form-control unicase-form-control text-input" id="id_password2" 
			value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
			name="password2">
			{% if forms.password2.errors %}
			<div class="alert alert-danger alert-dismissible fade show">{{forms.password2.errors}}</div>
			{% endif %}
		</div>
	  	<button type="submit" class="btn-upper btn btn-primary checkout-page-button">Зареєструватись</button>
	</form>
	
	
</div>	
<!-- create a new account -->			</div><!-- /.row -->
		</div>
        
        </div>
        </div>
        </div>
       
{% endblock content %}